import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "./composants/Nav";
import Footer from "./composants/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="overflow-x-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f5f7fa] min-h-screen flex flex-col overflow-x-hidden relative w-full`}
      >
        <Nav />
        <main className="flex-grow relative w-full">
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
